version: '3.5'

services:
  postgres_container:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 188.225.42.31:5433:5432
    networks:
      - nest_test
    restart: unless-stopped

  postgres_container_admin:
    container_name: postgres_container_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nest_test@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 127.0.0.1:5050:80
    networks:
      - nest_test
    restart: unless-stopped

networks:
  nest_test:
    driver: bridge


volumes:
  pgdata:
